### ISSUE TITLE
Transaction - Put link 

### ISSUE THREAD

**Issue by FauzaWayahAzhari** [Kelompok-4-Capstone-Alterra/go_women_center#103]
Pada transaction dengan counseling method video call, setelah dimasukkan link zoom response codenya 400.

Dokumentasi:
https://drive.google.com/file/d/1iUEB5Eiup5fjmZaKR-dp0CiC_sVGWro-/view?usp=sharing

**Comment by ThiccPan** [comment]
done ya, di pr #105  @FauzaWayahAzhari
