### ISSUE TITLE
Fix foldering issue

### ISSUE THREAD

**Issue by iBeccoo** [Kelompok-4-Capstone-Alterra/go_women_center#107]
#### Description
api route pada postman yang route ny sama namun ada 2 request

#### Screenshoots:
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/6c14276d-0d27-43da-93d0-fb00b51a2ecb)

![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/06732c2a-da53-4fba-959b-3612f66619e9)

**Comment by ThiccPan** [comment]
done mas
![Screenshot_2023-06-24_17-27-06](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/88238829/aae4b5ea-4f9a-41f5-8075-37a825d15907)

**Comment by ThiccPan** [comment]
untuk yang download perlu dikasih example kah? responsenya dari postmannya nggak ada soalnya kalau buat download file

**Comment by iBeccoo** [comment]
download itu macem export ke excel gt y ?

**Comment by ThiccPan** [comment]
iya kan ada export ke csv tuh, kalo didownload di postmannya nggak ngasih respon apa2

**Comment by iBeccoo** [comment]
oww gpp sih itu, rencananya mmg g di automation jg

**Comment by ThiccPan** [comment]
okee
