### ISSUE TITLE
Get counselor schedule with unexist counselor uuid succcess

### ISSUE THREAD

**Issue by iBeccoo** [Kelompok-4-Capstone-Alterra/go_women_center#115]
#### Description
return response code 200 with empty body when trying to get counselor schedule using unexist counselor uuid

#### Endpoint
GET domain/users/counselors/:id/schedule

#### Screenshoot
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/4fde7f11-7891-475a-b3c7-6b5b626abdfb)

no result when trying to search counselor with the uuid
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/debfe82c-03e2-480b-85e4-ea80a4290603)

**Comment by Ganes556** [comment]
yang itu jadi dirubah jadi kek gtu, permintaan dari flutternya

**Comment by iBeccoo** [comment]
bknnya klk uuid ny g exist, return error macem uuid not found gt

**Comment by Ganes556** [comment]
sudah di benerin yak, bisa di liat di #117

**Comment by iBeccoo** [comment]
okay fix ya
