### ISSUE TITLE
Admin career search for company email failed

### ISSUE THREAD

**Issue by iBeccoo** [Kelompok-4-Capstone-Alterra/go_women_center#52]
#### Description
Cant filter career result based on company email

#### Endpoint
GET https://13.210.163.192:8080/admin/careers 

#### Query param
search

#### Screenshots
without search filter
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/263945f0-b87e-489b-832d-4ad6eb5133ff)

with query param search=testupdate@update.com
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/c11c3e4c-461b-4f71-85cb-63c008fde10c)

**Comment by Saident** [comment]
done, bisa dicheck bang
