### ISSUE TITLE
Incorrect response message when success get all voucher

### ISSUE THREAD

**Issue by rinimzyy** [Kelompok-4-Capstone-Alterra/go_women_center#57]
Message response when success get all voucher must be “Successfully get all voucher”, but the response was “Successfully get new transaction”
Documentation:
https://drive.google.com/file/d/1oNz48bqR9yKHuN3Mef_nTCFXNQCDh25o/view?usp=drive_link

**Comment by ThiccPan** [comment]
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/88238829/03b97b98-83bc-44c6-9103-fac7c0b965a5)

fixed in the latest merge
