### ISSUE TITLE
Failed to delete article from admin

### ISSUE THREAD

**Issue by iBeccoo** [Kelompok-4-Capstone-Alterra/go_women_center#61]
#### Description
Failed to delete article from admin although uuid is valid, response message is internal server error

#### Endpoint
DELETE https://13.210.163.192:8080/admin/articles

#### Screenshots
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/bdfb3ccb-b6fc-489a-ac32-0bc31049189b)

uuid exist
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/486420e9-e164-4807-a73f-303b5d0da86d)

**Comment by Saident** [comment]
done, bisa dicheck bang

**Comment by iBeccoo** [comment]
okay done ya 
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/75a3e6b2-7016-4cef-9ce7-0bd1d398b457)
thank you
