### ISSUE TITLE
Failed to delete article from admin

### ISSUE THREAD

**Issue by iBeccoo** [Kelompok-4-Capstone-Alterra/go_women_center#63]
#### Description
It is possible to delete same article several times, article is not deleted from database

#### Endpoint
DELETE domain/admin/articles

#### Video
https://drive.google.com/file/d/16hYkamiNhSvJi19qZ1B4X_CkFK_0S13x/view?usp=drive_link

**Comment by Saident** [comment]
sudah bisa bang, bisa dicheck lagi, keknya kemarin itu lagi proses deploy jadi belum keupdate yang baru

**Comment by iBeccoo** [comment]
masih sma mas, record ny ttp ada

**Comment by Saident** [comment]
sorry2 bang, ada yang kelewat 1 wkwkwk
harusnya udah sekarang

**Comment by iBeccoo** [comment]
okay done ya thank you
