### ISSUE TITLE
Failed to get transaction list from user

### ISSUE THREAD

**Issue by iBeccoo** [Kelompok-4-Capstone-Alterra/go_women_center#66]
#### Description
Get all transaction from user return empty value, when create is successful and read with id from created transaction return transaction data

#### Endpoint
GET domain/users/transactions

#### Screenshots
create success
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/868443e0-8a9c-44d9-86b8-357e693105f7)

read success
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/5dbc5e3d-480d-4afb-ad4c-f5ebc1d0b6df)

get all return empty value
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/df0d22bf-c136-4492-8423-8086911a6834)

**Comment by ThiccPan** [comment]
get all doesn't show unpaid transaction, the get by id is used to check whether the transaction has been paid or not (to show payment status popup)

**Comment by ThiccPan** [comment]
> get all doesn't show unpaid transaction, the get by id is used to check whether the transaction has been paid or not (to show payment status popup)

unpaid transaction have "pending" as the status

**Comment by iBeccoo** [comment]
when implemented by frontend, from where frontend can have the list of transaction ids? that will be used to check whether a transaction has already been paid

**Comment by ThiccPan** [comment]
for the front end get all feature, it will show all status including the pending one, that can be used to check the payment status

**Comment by iBeccoo** [comment]
okay thank you
