### ISSUE TITLE
[MINOR] Internal server error when get counselor schedule

### ISSUE THREAD

**Issue by iBeccoo** [Kelompok-4-Capstone-Alterra/go_women_center#67]
#### Description
Response status with 500 Internal server error, when use unexist uuid

#### Endpoint
GET domain/users/counselors/:id/schedules

#### Screeenshoot
![image](https://github.com/Kelompok-4-Capstone-Alterra/go_women_center/assets/101125593/59833715-66ed-484f-a224-3f96387dcced)

**Comment by Ganes556** [comment]
siap bg otw benerin

**Comment by Ganes556** [comment]
udah update bisa di cek

**Comment by iBeccoo** [comment]
okay done ya thank you
